{% set name = "Flask-AutoIndex" %}
{% set version = "0.6.1" %}
{% set hash = "a789e4033b984b8240690b80e055d7dd4f04785c5fe9431c31b2c27180d2076d" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  noarch: python
  number: {{ build }}
  script: python -m pip install --no-deps --ignore-installed . --verbose

requirements:
  host:
    - python
    - pip

  run:
    - python
    - flask >=0.8,<0.12
    - flask-silk >=0.2
    - future >=0.13.0

test:
  imports:
    - flask_autoindex

about:
  home: https://github.com/sublee/flask-autoindex
  license_file: LICENSE
  license: BSD-3-Clause
  license_family: BSD
  summary: 'Generates index page like mod_autoindex'
  dev_url: https://github.com/sublee/flask-autoindex

extra:
  recipe-maintainers:
    - isuruf
