travis:
  secure:
    BINSTAR_TOKEN: NCkdy999JjDilKhpHLaCSEkl4etmTsnUZoH9y29uw55lXBM5xbZtKatVDNBZ/hn+Qb00rzZpo/s0qhsNiV2DKiIHpFCRrTOMgaoGdHqxBReNaJjIAQy8XdXDWmEmIl4cGtFfR1d5hRKPnaMzUTTvQLNiObhd5+rXp55KyPFlzACubLARf+tB6lsvZGsVSTQY9n2LGzX4LCve0tUAMExwX+J+19iW6xmH5bY2y7syCY4j9Ta+EFkW/8g0VSiENwE86HwAOjIiSKoibsB9wvE17sT784+DEcN19F1lnxK8HabP+2neNopHFS0ecHPLIj6Sx4aw4y+iFuWwHuxwJ6eAi28XN1uDF6lGBQ4MZCr7hRiz/amqwSkHI+bae5TJ6gw642pgKqPB3l9k9+oV4kayzPe/tDtnJNxOPAUqoh1bg1np1CeetSBoLbW8ubHBKxAhUZ7DCoykUOZ3gnE5qsH5zDCyL4IalIFdNr4WQmTJB9wwKoYH3gmoZrwPbftjJARWabnT7tkWgECuScuQ0NDNIhmXx5ydxMr9IpZ1sv6HzxFcBT0MmrpIWSCSVDLvxf6kUs5f5Nk8SGCBWEc0F1pANZG640rADO49HX7Pcyk8n/PKVsGSEWXreXmzo2hedmwrUgnMUFa3xEi1aC+yADLxjy43q8Q1wFC9tPww6eN2IPQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
