travis:
  secure:
    BINSTAR_TOKEN: i6oFKL+lpEQWN6t1FqWkxtDz/NSAZ/xdw/zzMrRe0VZxl88NHQJVV5uTh9oEJlKuFgwWPuTmDXgWzlX8liXsW+87kK4CTl2tYpxTjajyD63ocTyu2R5QRabtyg/2sr5+WjINRVS6GKuhsYMzOTwq73r5xJozqq9b8i6iey2aJQCd1yYOBQt4PBZOOaRjShHYqMZf7ZUutQ8OnOyqaGXqkvYHSIYM/GSL1wPQEquwTUPMoOM+2vxuQWPRfoDC1F314tkL7+Dzd53jFcsy5FBX8tOFF2NyjqrtwspuM+gAstAZDYLK+KVDTK/402uYMglBwLdRH0q9YgQHmO4gJumloyfNKdhT9oT/Cq9U81lER+lY6V1V/4JaW8zsaKvW2JDFqJ6pfOiSy3/r9gRMN4YvFUWratNVAJrJUhN9zT9JHs6gwhGcOhAAM/oKsla7Vu/W/RZZQYluh0IKziLbqE/5q/ml3GM3NfaGyeNBBsQTSMnyXA2HywQD1PzQyv22nwS+8Nhb8gMZjU3AOhQtntrwdCbCKgptF91uGXHbs/NJscoz2p2aKDkGkA5TplfycnYFZNnoCtvdKP5S0G9Ti8QxpvKVGWy5QNMDsOnxuzQVFSEsJ/yV7ijHixzRqEvxLDjquzDRdrUTUxN2sk1d3dcQ89SXNv8SBqZSL5Msaw8in84=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
