travis:
  secure:
    BINSTAR_TOKEN: dYKXC5E+jtD7fSH8CbKZl2HEW+047GAi5bOGwh5ybjAttRAKXZLo5cYaQHJUmhBQVf1Lo/IVMrrzmjbHdZ/hBqqGfnFZnLqam1KkGUUOZ5tl0IClxl5miLunEfydmlG1hFv57VJhSzM3cGhn8IEurFdzcVgXmLWfbGrOa3yXW3miooJEx7P0YNqifjrZk3x4BowhtNEO2CFPoA6hajS3udzsqTUlJ5C2dMuupDSowODtIh825VdJAvmnJ2FxVQ8vQfTiHgjOFV+eLW661U3nQ5i+8lLxJTu4gdTKadnC2B1tEEy1SzIjjU9/SlCbx9P7OsBzbp2kobdtEq7dL+M3RzmluUwwk6z5nlJjj+hS6eOXM0yn1FbxjuSGWQ0pEjaDt8RdSkXVULUQHGG31S6pQrlN2jCTBgNdrtQeuqvjGLQy+/t3I9NPIawgFxNzAUO3NWUy8z0HJJiz0ZywJLU07TABdwb9+ICRvba8xVqLFdRUaL/+lVsfIMrvNidbCxh80jqBDZCYzfyEEF9Wm3TITuzC7dS+dTS7/o9fTFZkkx+kfwqSnpRsX4FiZWAYWU+jisITvOCQgovDbctS14X63xz9xzvfZh2OrywwxhIfhYcer302q28VKZKpz+1WYutPChPQVBwppzApyXQeajZjLJw31jFmkRuzvCAQHz8HKd8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
